FROM bellsoft/liberica-runtime-container:jre-21-glibc

RUN apk update && \
    apk add --no-cache --no-scripts \
        nginx \
        bash \
        fontconfig \
        ttf-dejavu \
    && rm -rf /var/cache/apk/* \
    && mkdir -p /run/nginx /var/log/nginx /var/tmp/nginx /etc/nginx/conf.d

COPY main/manager-web/public/generator/static/fonts/*.ttf /usr/share/fonts/
RUN fc-cache -f -v

RUN addgroup -S tbot && adduser -S tbot -G tbot && \
    mkdir -p /var/cache/nginx /var/run/nginx && \
    chown -R tbot:tbot /var/cache/nginx /var/run/nginx /var/log/nginx /usr/share/nginx/html /app /run/nginx /var/tmp/nginx /etc/nginx/conf.d

COPY docs/docker/nginx.conf /etc/nginx/nginx.conf
COPY main/manager-web/dist /usr/share/nginx/html
COPY main/manager-api/target/tbot-esp32-api.jar /app/tbot-esp32-api.jar

EXPOSE 8002

COPY docs/docker/start.sh /start.sh
RUN chmod +x /start.sh
USER tbot
CMD ["/start.sh"]
