"""Stable semantic embodied intents consumed by the Task 02 dispatcher."""

from enum import Enum


class EmbodiedIntent(str, Enum):
    REST_WARM = "REST_WARM"
    GREET_SMALL = "GREET_SMALL"
    INVITE_CHILD = "INVITE_CHILD"
    PRESENT_CENTER = "PRESENT_CENTER"
    PRESENT_LEFT = "PRESENT_LEFT"
    PRESENT_RIGHT = "PRESENT_RIGHT"
    LISTEN_STILL = "LISTEN_STILL"
    THINK_CURIOUS = "THINK_CURIOUS"
    ACKNOWLEDGE_STORY = "ACKNOWLEDGE_STORY"
    MODEL_WORD = "MODEL_WORD"
    ENCOURAGE_SMALL = "ENCOURAGE_SMALL"
    TRY_DIFFERENT_WAY = "TRY_DIFFERENT_WAY"
    CELEBRATE_RECALL = "CELEBRATE_RECALL"
    CELEBRATE_MASTERY = "CELEBRATE_MASTERY"
    COMFORT_CALM = "COMFORT_CALM"
    PAUSE_CHOICE = "PAUSE_CHOICE"
    GOODBYE_SMALL = "GOODBYE_SMALL"
