const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const helpers=require('../../src/components/lesson/lesson-visual-selection');
const source=fs.readFileSync(require('node:path').join(__dirname,'../../src/components/lesson/CourseModeVisualSelection.vue'),'utf8');
const script=source.split('<script>')[1].split('</script>')[0].replace(/^import .*;$/gm,'').replace('export default','return');
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const snap=(lessonId='A')=>({lessonId,checksum:'a'.repeat(64),visualChecksum:'b'.repeat(64),refs:[{stepKey:'a',slot:'backgroundScene',assetVersionId:id(1)},...helpers.COURSE_MODE_PHASES.map((p,i)=>({stepKey:'a',slot:`robotOverlay.${p.id}`,assetVersionId:id(i+10)}))],cinematicPhases:[]});
function setup(){const reads=[],writes=[],events=[];const component=new Function('Api',...Object.keys(helpers),script)({lesson:{getLessonVisuals:(...a)=>reads.push(a),applyLessonVisuals:(...a)=>writes.push(a)}},...Object.values(helpers));const e={...component.data(),...component.methods,lessonId:'A',disabled:false,isDraft:true,assets:[],contract:{activities:[]},$emit:(...a)=>events.push(a)};for(const [k,get]of Object.entries(component.computed))Object.defineProperty(e,k,{get:()=>get.call(e)});e.load();reads[0][1](snap());return {e,reads,writes,events};}
test('visual editor reads, saves both tokens, then reads persisted state',()=>{const {e,reads,writes}=setup();e.draft.robotAssetVersionIds.teach=id(99);e.save();assert.equal(writes.length,1);assert.equal(writes[0][1].expectedVisualChecksum,'b'.repeat(64));assert.equal(writes[0][1].robotAssetVersionIds.walk,id(11));writes[0][2]({lessonId:'A',checksum:'c'.repeat(64),contractChecksum:'a'.repeat(64),visualChecksum:'d'.repeat(64)});assert.equal(reads.length,2);assert.equal(e.saving,true);const persisted=snap();persisted.visualChecksum='d'.repeat(64);persisted.refs.find(r=>r.slot==='robotOverlay.teach').assetVersionId=id(99);reads[1][1](persisted);assert.equal(e.saving,false);assert.equal(e.dirty,false);});
for(const status of [0,401,403,409,500])test(`visual failure ${status} retains selection until explicit readback`,()=>{const {e,writes,reads}=setup();e.draft.robotAssetVersionIds.teach=id(99);e.save();writes[0][3]('failure',{status});assert.equal(e.draft.robotAssetVersionIds.teach,id(99));assert.equal(e.dirty,true);assert.ok(e.error);assert.equal(reads.length,1);});
test('late visual read after lesson navigation is ignored',()=>{const {e,reads}=setup();e.load(true);e.lessonId='B';reads.at(-1)[1](snap());assert.equal(e.snapshot.lessonId,'A');assert.equal(e.comparison,null);});
test('comparison does not replace local draft before explicit choice',()=>{const {e,reads}=setup();e.draft.robotAssetVersionIds.teach=id(99);e.load(true);const remote=snap();remote.visualChecksum='d'.repeat(64);reads.at(-1)[1](remote);assert.equal(e.draft.robotAssetVersionIds.teach,id(99));assert.equal(e.snapshot.visualChecksum,'b'.repeat(64));e.keepDraft();assert.equal(e.snapshot.visualChecksum,'d'.repeat(64));assert.equal(e.draft.robotAssetVersionIds.teach,id(99));});

test('different readback after save retains draft and requires comparison',()=>{const {e,reads,writes}=setup();e.draft.robotAssetVersionIds.teach=id(99);e.save();writes[0][2]({lessonId:'A',contractChecksum:'a'.repeat(64),visualChecksum:'d'.repeat(64)});reads[1][1](snap());assert.equal(e.draft.robotAssetVersionIds.teach,id(99));assert.equal(e.conflict,true);assert.equal(e.savedMessage,'');assert.ok(e.comparison);});
