package tbot.modules.agent.dto;

import java.io.Serializable;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;

/**
 * Agent createDTO
 * Dedicated to adding agents, excludingid,agentCodeandsortFields automatically generated by system/Set default value
 */
@Data
@Schema(description = "Agent create object")
public class AgentCreateDTO implements Serializable {
    private static final long serialVersionUID = 1L;

    @Schema(description = "Agent name", example = "Customer service assistant")
    @NotBlank(message = "Agent name cannot be empty")
    private String agentName;
}